// <auto-generated />
namespace Shedule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MigrateDb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrateDb2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021118059_MigrateDb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
